import {firebaseConfig} from "./firebase-config.js";
import {THEME_PRESETS, MONTHLY_THEMES} from "./theme-presets.js";
const DEFAULT={hero:{eyebrow:"a little corner of the internet, kept warm",heading:"Where handwritten letters, moonlit stories, and golden sunflowers bloom.",lead:"Welcome to Moony Sunflowers — a soft place for words, paper, tiny dreams, and the people who make them worth writing.",letterGreeting:"Dear little reader,",letterBody:"If you've wandered here looking for a quiet place, you may stay awhile. There are stories tucked in drawers, and a moon that never minds if you arrive late.",signature:"— Dimple ♡"},books:[{title:"Your Book Title",kind:"featured book",description:"Replace this with the real blurb.",cover:"",button:"Order / Support"},{title:"Another Book Title",kind:"co-authored",description:"Add anthology details.",cover:"",button:"Order / Support"}],stories:[{category:"poetry",title:"The Moon Keeps Letters",description:"For every unsent thing, there is a night sky willing to keep it safe.",body:"Some nights, I imagine the moon is an old post office."}],magazine:[{issue:"Issue 01",title:"Moon Notes — Issue 01",date:"January 2026",url:"",cover:""}],links:{snailMail:"",community:"",instagramDm:"https://ig.me/m/dimple_writes07",instagram:"https://www.instagram.com/dimple_writes07/",goodreads:"",amazon:""},payment:{upi:"dimplelokhande@fam",name:"Dimple"},theme:{base:"#CDE0C9",accent:"#E8A838",paper:"#FAF6EE",ink:"#2C221E",plum:"#3B222E",logo:"assets/moony_sunflowers_logo.png",authorPhoto:"assets/dimple_author_photo.png",qr:"assets/upi_scanner_qr.jpeg",headingFont:"Playfair Display",bodyFont:"Plus Jakarta Sans",scriptFont:"Caveat",radius:"28px",mode:"manual",active:"evergreen-library"},seo:{title:"Moony Sunflowers | Books, Stories & Snail Mail by Dimple",description:"Moony Sunflowers — a cozy digital sanctuary by Dimple.",canonical:""}};
let state=JSON.parse(localStorage.getItem("moonyAdminState")||"null")||structuredClone(DEFAULT);
const path=(o,p,v)=>{let a=p.split("."),x=o;for(let i=0;i<a.length-1;i++)x=x[a[i]];if(v!==undefined)x[a.at(-1)]=v;return x[a.at(-1)]};
const esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function hydrate(){document.querySelectorAll("[data-key]").forEach(e=>e.value=path(state,e.dataset.key)||"");document.getElementById("logoPreview").src=state.theme.logo||"assets/moony_sunflowers_logo.png";document.getElementById("authorPhotoPreview").src=state.theme.authorPhoto||"assets/dimple_author_photo.png";document.getElementById("qrPreview").src=state.theme.qr||"assets/upi_scanner_qr.jpeg";renderLists();renderThemeStudio()}
function collect(){document.querySelectorAll("[data-key]").forEach(e=>path(state,e.dataset.key,e.value))}
function save(){collect();localStorage.setItem("moonyAdminState",JSON.stringify(state));document.body.dataset.saved="1";alert(firebaseConfig?"Saved locally. Add the Firebase sync section in your project after configuring Firebase.":"Saved to this phone/browser. Connect Firebase to publish live.");}
function list(kind){let arr=state[kind==="book"?"books":kind==="story"?"stories":"magazine"],box=document.getElementById(kind==="book"?"booksList":kind==="story"?"storiesList":"magList");box.innerHTML="";arr.forEach((x,i)=>{let fields=kind==="book"?`<label>Title<input data-arr="books" data-i="${i}" data-f="title" value="${esc(x.title)}"></label><label>Type<input data-arr="books" data-i="${i}" data-f="kind" value="${esc(x.kind)}"></label><label>Description<textarea data-arr="books" data-i="${i}" data-f="description">${esc(x.description)}</textarea></label><label>Cover image URL<input data-arr="books" data-i="${i}" data-f="cover" value="${esc(x.cover)}</label>`:kind==="story"?`<label>Category<select data-arr="stories" data-i="${i}" data-f="category"><option>poetry</option><option>short</option><option>musing</option><option>review</option></select></label><label>Title<input data-arr="stories" data-i="${i}" data-f="title" value="${esc(x.title)}"></label><label>Card description<textarea data-arr="stories" data-i="${i}" data-f="description">${esc(x.description)}</textarea></label><label>Reader text<textarea data-arr="stories" data-i="${i}" data-f="body">${esc(x.body)}</textarea></label>`:`<label>Issue<input data-arr="magazine" data-i="${i}" data-f="issue" value="${esc(x.issue)}"></label><label>Title<input data-arr="magazine" data-i="${i}" data-f="title" value="${esc(x.title)}"></label><label>Date<input data-arr="magazine" data-i="${i}" data-f="date" value="${esc(x.date)}"></label><label>Viewer / PDF URL<input data-arr="magazine" data-i="${i}" data-f="url" value="${esc(x.url)}"></label><label>Cover image URL<input data-arr="magazine" data-i="${i}" data-f="cover" value="${esc(x.cover)}</label>`;box.insertAdjacentHTML("beforeend",`<div class="item"><div class="itemtop"><b>${kind==="book"?"Book":kind==="story"?"Writing":"Issue"} ${i+1}</b><button class="remove" data-remove="${kind}" data-i="${i}">Remove</button></div>${fields}</div>`);});box.querySelectorAll("select").forEach((e,i)=>e.value=arr[i].category);box.querySelectorAll("[data-arr]").forEach(e=>e.oninput=()=>state[e.dataset.arr][+e.dataset.i][e.dataset.f]=e.value);box.querySelectorAll("[data-remove]").forEach(e=>e.onclick=()=>{let a=e.dataset.remove==="book"?"books":e.dataset.remove==="story"?"stories":"magazine";state[a].splice(+e.dataset.i,1);list(e.dataset.remove)})}
function renderLists(){list("book");list("story");list("mag")}

function themeData(id){return THEME_PRESETS[id] ? {...THEME_PRESETS[id],active:id} : (state.customThemes||[]).find(t=>t.id===id)}
function applyThemeData(t){if(!t)return;Object.assign(state.theme,{...t,logo:state.theme.logo||"assets/moony_sunflowers_logo.png",authorPhoto:state.theme.authorPhoto||"assets/dimple_author_photo.png",qr:state.theme.qr||"assets/upi_scanner_qr.jpeg"});hydrate()}
function renderThemeStudio(){
 const box=document.getElementById("themePresets"),custom=document.getElementById("customThemes"); if(!box||!custom)return;
 box.innerHTML=Object.entries(THEME_PRESETS).map(([id,t])=>`<button class="theme-card ${state.theme.active===id?"selected":""}" data-theme="${id}"><span class="swatches"><i style="background:${t.base}"></i><i style="background:${t.accent}"></i><i style="background:${t.paper}"></i><i style="background:${t.plum}"></i></span><b>${esc(t.name)}</b><small>${esc(t.group)}</small></button>`).join("");
 const customs=state.customThemes||[];
 custom.innerHTML=customs.length?customs.map((t,i)=>`<div class="theme-card custom-card ${state.theme.active===t.id?"selected":""}"><button data-custom-theme="${i}" class="theme-card-main"><span class="swatches"><i style="background:${t.base}"></i><i style="background:${t.accent}"></i><i style="background:${t.paper}"></i><i style="background:${t.plum}"></i></span><b>${esc(t.name)}</b><small>Custom theme</small></button><button class="remove-theme" data-delete-theme="${i}">×</button></div>`).join(""):`<p class="muted empty">No custom themes yet. Make one above ✦</p>`;
 const label=document.getElementById("activeThemeLabel"); if(label)label.textContent=state.theme.name||THEME_PRESETS[state.theme.active]?.name||"Custom design";
 box.querySelectorAll("[data-theme]").forEach(b=>b.onclick=()=>applyThemeData(themeData(b.dataset.theme)));
 custom.querySelectorAll("[data-custom-theme]").forEach(b=>b.onclick=()=>applyThemeData(customs[+b.dataset.customTheme]));
 custom.querySelectorAll("[data-delete-theme]").forEach(b=>b.onclick=()=>{customs.splice(+b.dataset.deleteTheme,1);state.customThemes=customs;renderThemeStudio()});
}
document.getElementById("applyMonthly")?.addEventListener("click",()=>{const id=MONTHLY_THEMES[new Date().getMonth()+1];applyThemeData(themeData(id));state.theme.mode="monthly";document.querySelector('input[name="themeMode"][value="monthly"]').checked=true});
document.querySelectorAll('input[name="themeMode"]').forEach(r=>r.addEventListener("change",()=>state.theme.mode=r.value));
document.getElementById("saveCustomTheme")?.addEventListener("click",()=>{collect();const name=(document.getElementById("customThemeName").value||"My Moony Theme").trim();const id="custom-"+Date.now();const t={...state.theme,name,id};state.customThemes=state.customThemes||[];state.customThemes.push(t);state.theme.active=id;state.theme.name=name;localStorage.setItem("moonyAdminState",JSON.stringify(state));document.getElementById("customThemeName").value="";renderThemeStudio();alert(`“${name}” saved ✦`)});
document.getElementById("applyCustomTheme")?.addEventListener("click",()=>{collect();hydrate()});
document.getElementById("duplicateTheme")?.addEventListener("click",()=>{collect();document.getElementById("customThemeName").value=(state.theme.name||"My Moony Theme")+" — copy"});

document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{
function themeData(id){return THEME_PRESETS[id] ? {...THEME_PRESETS[id],active:id} : (state.customThemes||[]).find(t=>t.id===id)}
function applyThemeData(t){if(!t)return;Object.assign(state.theme,{...t,logo:state.theme.logo||"assets/moony_sunflowers_logo.png",authorPhoto:state.theme.authorPhoto||"assets/dimple_author_photo.png",qr:state.theme.qr||"assets/upi_scanner_qr.jpeg"});hydrate()}
function renderThemeStudio(){
 const box=document.getElementById("themePresets"),custom=document.getElementById("customThemes"); if(!box||!custom)return;
 box.innerHTML=Object.entries(THEME_PRESETS).map(([id,t])=>`<button class="theme-card ${state.theme.active===id?"selected":""}" data-theme="${id}"><span class="swatches"><i style="background:${t.base}"></i><i style="background:${t.accent}"></i><i style="background:${t.paper}"></i><i style="background:${t.plum}"></i></span><b>${esc(t.name)}</b><small>${esc(t.group)}</small></button>`).join("");
 const customs=state.customThemes||[];
 custom.innerHTML=customs.length?customs.map((t,i)=>`<div class="theme-card custom-card ${state.theme.active===t.id?"selected":""}"><button data-custom-theme="${i}" class="theme-card-main"><span class="swatches"><i style="background:${t.base}"></i><i style="background:${t.accent}"></i><i style="background:${t.paper}"></i><i style="background:${t.plum}"></i></span><b>${esc(t.name)}</b><small>Custom theme</small></button><button class="remove-theme" data-delete-theme="${i}">×</button></div>`).join(""):`<p class="muted empty">No custom themes yet. Make one above ✦</p>`;
 const label=document.getElementById("activeThemeLabel"); if(label)label.textContent=state.theme.name||THEME_PRESETS[state.theme.active]?.name||"Custom design";
 box.querySelectorAll("[data-theme]").forEach(b=>b.onclick=()=>applyThemeData(themeData(b.dataset.theme)));
 custom.querySelectorAll("[data-custom-theme]").forEach(b=>b.onclick=()=>applyThemeData(customs[+b.dataset.customTheme]));
 custom.querySelectorAll("[data-delete-theme]").forEach(b=>b.onclick=()=>{customs.splice(+b.dataset.deleteTheme,1);state.customThemes=customs;renderThemeStudio()});
}
document.getElementById("applyMonthly")?.addEventListener("click",()=>{const id=MONTHLY_THEMES[new Date().getMonth()+1];applyThemeData(themeData(id));state.theme.mode="monthly";document.querySelector('input[name="themeMode"][value="monthly"]').checked=true});
document.querySelectorAll('input[name="themeMode"]').forEach(r=>r.addEventListener("change",()=>state.theme.mode=r.value));
document.getElementById("saveCustomTheme")?.addEventListener("click",()=>{collect();const name=(document.getElementById("customThemeName").value||"My Moony Theme").trim();const id="custom-"+Date.now();const t={...state.theme,name,id};state.customThemes=state.customThemes||[];state.customThemes.push(t);state.theme.active=id;state.theme.name=name;localStorage.setItem("moonyAdminState",JSON.stringify(state));document.getElementById("customThemeName").value="";renderThemeStudio();alert(`“${name}” saved ✦`)});
document.getElementById("applyCustomTheme")?.addEventListener("click",()=>{collect();hydrate()});
document.getElementById("duplicateTheme")?.addEventListener("click",()=>{collect();document.getElementById("customThemeName").value=(state.theme.name||"My Moony Theme")+" — copy"});

document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active")});
document.querySelectorAll(".save").forEach(b=>b.onclick=save);
document.getElementById("addBook").onclick=()=>{state.books.push({title:"New Book",kind:"new",description:"",cover:"",button:"Order / Support"});list("book")};
document.getElementById("addStory").onclick=()=>{state.stories.push({category:"poetry",title:"New Writing",description:"",body:""});list("story")};
document.getElementById("addMag").onclick=()=>{state.magazine.push({issue:"New Issue",title:"New Issue",date:"",url:"",cover:""});list("mag")};
async function image(file){return new Promise((r,j)=>{let f=new FileReader();f.onload=()=>r(f.result);f.onerror=j;f.readAsDataURL(file)})}
document.getElementById("logo").onchange=async e=>{if(e.target.files[0]){state.theme.logo=await image(e.target.files[0]);document.getElementById("logoPreview").src=state.theme.logo}};
document.getElementById("qr").onchange=async e=>{if(e.target.files[0]){state.theme.qr=await image(e.target.files[0]);document.getElementById("qrPreview").src=state.theme.qr}};
document.getElementById("authorPhoto").onchange=async e=>{if(e.target.files[0]){state.theme.authorPhoto=await image(e.target.files[0]);document.getElementById("authorPhotoPreview").src=state.theme.authorPhoto}};
document.getElementById("export").onclick=()=>{collect();let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="moony-sunflowers-settings.json";a.click()};
document.getElementById("import").onchange=async e=>{state=JSON.parse(await e.target.files[0].text());localStorage.setItem("moonyAdminState",JSON.stringify(state));hydrate()};
document.getElementById("reset").onclick=()=>{state=structuredClone(DEFAULT);localStorage.removeItem("moonyAdminState");hydrate()};
document.getElementById("login").onclick=async()=>{if(!firebaseConfig){document.getElementById("status").textContent="Demo editor opened. Firebase is not connected yet; connect it for secure Google login + live publishing.";document.getElementById("auth").hidden=true;document.getElementById("app").hidden=false;return}document.getElementById("status").textContent="Firebase config detected. Complete the Google Auth code/rules setup in ADMIN_SETUP.md."};
hydrate();
